sudo:
  false

language:
 node_js

node_js:
  - 0.10.31

script:
  - npm run prepare
  - npm run lint

after_success:
  - bash deploy_scripts/publish.sh

notifications:
  email:
    recipients:
      - mackn@mackn.org
    on_success: always
    on_failure: always
